### ISSUE TITLE
NameError - undefined local variable or method `scope_stack'

### ISSUE THREAD

**Issue by mrchess** [digitalplaywright/mongoid-slug#192]
After upgrading to Mongoid 5, when trying to use `mongoid-slug 4.0.0` I get this error:

```
NameError - undefined local variable or method `scope_stack' for Event:Class:
  mongoid_slug (4.0.0) lib/mongoid/slug.rb:138:in `queryable'
  mongoid (5.0.0) lib/mongoid/scopable.rb:209:in `with_default_scope'
  (eval):2:in `where'
  mongoid (5.0.0) lib/mongoid/relations/referenced/many.rb:564:in `criteria'
  mongoid (5.0.0) lib/mongoid/relations/metadata.rb:181:in `criteria'
  mongoid (5.0.0) lib/mongoid/relations/builders/referenced/many.rb:20:in `build'
  mongoid (5.0.0) lib/mongoid/relations/accessors.rb:43:in `create_relation'
  mongoid (5.0.0) lib/mongoid/relations/accessors.rb:26:in `__build__'
  mongoid (5.0.0) lib/mongoid/relations/accessors.rb:104:in `block (2 levels) in get_relation'
  mongoid (5.0.0) lib/mongoid/threaded/lifecycle.rb:130:in `_loading'
  mongoid (5.0.0) lib/mongoid/relations/accessors.rb:100:in `block in get_relation'
  mongoid (5.0.0) lib/mongoid/threaded/lifecycle.rb:89:in `_building'
  mongoid (5.0.0) lib/mongoid/relations/accessors.rb:99:in `get_relation'
  mongoid (5.0.0) lib/mongoid/relations/accessors.rb:187:in `block in getter'
```

**Comment by dblock** [comment]
Mongoid-slug 5.x supports Mongoid 5, mongoid-slug 4.x does not.

**Comment by mrchess** [comment]
Ah got it. Thanks.
